/* tslint:disable:object-literal-sort-keys */
export default {
    UPDATE_IS_AUTHENTICATE: "UPDATE_IS_AUTHENTICATE",
    UPDATE_AUTH_ERROR_MESEAGE: "UPDATE_AUTH_ERROR_MESEAGE",
    UPDATE_HOME_COUNT: "UPDATE_HOME_COUNT",
    UPDATE_HOSTS: "UPDATE_HOSTS",
    UPDATE_TAGS: "UPDATE_TAGS",
    UPDATE_ACTIVE_VIEW: "UPDATE_ACTIVE_VIEW",
    UPDATE_ARTICLES: "UPDATE_ARTICLES",
    UPDATE_SEARCH_ARTICLES: "UPDATE_SEARCH_ARTICLES",
};
/* tslint:enable:object-literal-sort-keys */
